name = "hackernews"
# main = "src/index.cjs"
compatibility_date = "2022-04-15"
type = "javascript"
# entry-point = "./_worker.js"

# bucket = "./dist/assets"

# [build.upload]
# format = "modules"
# main = "./worker.mjs"

# You do not need to include these default rules in your `wrangler.toml`, they are implicit.
# The default rules are treated as the last two rules in the list.

# [[rules]]
# format = "modules"
# main = "./_worker.js"

# [[rules]]
# type = "CommonJS"
# globs = ["**/*.js", "**/*.cjs"]

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js", "**/*.mjs"]